allowBuilds:
  electron: true
  electron-winstaller: true
  esbuild: true
  node-pty: true
minimumReleaseAgeExclude:
  - lucide-react@1.43.0
overrides:
  rolldown: 1.2.6
patchedDependencies:
  '@xterm/addon-search@0.16.0': patches/@xterm__addon-search@0.16.0.patch
