import assert from 'node:assert/strict'
import {mkdirSync,readFileSync,writeFileSync,realpathSync,readdirSync} from 'node:fs'
import {execFileSync} from 'node:child_process'
import {join,resolve,dirname} from 'node:path'
import {pathToFileURL} from 'node:url'
import {parseArgs} from 'node:util'
import {hash,sourceIdentity,validateOptions} from './workspace-baseline.mjs'
import {cleanupOwnedSmokeDaemon,delay} from '../helpers/smoke-processes.mjs'
const {values}=parseArgs({options:{app:{type:'string'},profile:{type:'string'},evidence:{type:'string'},playwright:{type:'string'},graph:{type:'string'},qmd:{type:'string'},lance:{type:'string'},history:{type:'string'},backlog:{type:'string'}}})
const {app:executable,resources,profile,evidence}=validateOptions(values)
mkdirSync(profile);mkdirSync(evidence);mkdirSync(join(profile,'fixture'));const project=realpathSync(join(profile,'fixture'))
for(let n=0;n<200;n++)writeFileSync(join(project,`source-${n}.md`),'native resource controls fixture\n'.repeat(1000))
for(const args of [['init','-b','main'],['config','user.email','fixture@example.test'],['config','user.name','Fixture'],['add','.'],['commit','-m','Fixture']])execFileSync('git',args,{cwd:project,stdio:'ignore'})
const {_electron}=await import(pathToFileURL(resolve(values.playwright)))
const {callRuntime}=await import(pathToFileURL(join(resources,'dist-cli/cli/rpc-client.js')))
const invoke=async(method,params={})=>{const result=await callRuntime(method,params,profile,45000);assert(result.ok,result.error);return result.result}
const env={...process.env,DONWELLS_USER_DATA:profile};for(const key of Object.keys(env))if(key.startsWith('DONWELLS_DOCUMENT_')||['DONWELLS_HISTORY_BINARY','DONWELLS_HISTORY_ROOTS','DONWELLS_BACKLOG_BINARY','DONWELLS_CODE_GRAPH_BINARY','DONWELLS_BROWSER_TOOL_PACKAGE','DONWELLS_BROWSER_TOOL_EXECUTABLE','DONWELLS_COMPUTER_TOOL_BINARY','ELECTRON_RUN_AS_NODE','ELECTRON_RENDERER_URL','DONWELLS_SMOKE'].includes(key))delete env[key]
const report={source:sourceIdentity(),artifactSha256:hash(readFileSync(join(resources,'app.asar'))),project}
let app,page
const open=async()=>{app=await _electron.launch({executablePath:executable,env,timeout:30000});page=await app.firstWindow();await page.getByRole('navigation',{name:'Workspace tools'}).waitFor()}
const inspect=()=>page.evaluate(path=>window.donwells.projectDoctorInspect(path),project)
try{
 await open();await invoke('settings.set',{theme:'dark'});await invoke('repo.add',{dir:project});await page.getByRole('button',{name:/Main checkout/}).click();await invoke('ui.settings.open',{section:'agents'})
 const panel=page.getByRole('region',{name:'Project tools'});await panel.getByText('Available cache disk:',{exact:false}).waitFor()
 const graph=panel.locator('details').filter({has:page.locator('summary').filter({hasText:'Code graph'})}).first();await graph.locator(':scope > summary').click()
 await graph.getByLabel('Code graph executable',{exact:false}).fill('/missing/admitted-binary');await panel.getByRole('button',{name:'Apply configuration and stop services'}).click();await panel.getByText('Missing path',{exact:true}).waitFor()
 await graph.getByLabel('Code graph executable',{exact:false}).fill(resolve(values.graph));await panel.getByText('Configuration changes',{exact:true}).waitFor();await page.screenshot({path:join(evidence,'configuration-diff.png')});await panel.getByRole('button',{name:'Apply configuration and stop services'}).click()
 await graph.getByRole('button',{name:'Retry readiness'}).click();await graph.locator(':scope > summary').filter({hasText:'ready'}).waitFor({timeout:45000});report.nativeGraphReady=(await inspect()).services.find(service=>service.id==='code-graph');assert.equal(report.nativeGraphReady.status,'ready')
 await graph.getByLabel('Enabled for this project').uncheck();await panel.getByRole('button',{name:'Apply configuration and stop services'}).click();await graph.locator(':scope > summary').filter({hasText:'disabled'}).waitFor()
 const documents=panel.locator('details').filter({has:page.locator('summary').filter({hasText:'Document retrieval'})}).first();await documents.locator(':scope > summary').click();await documents.getByLabel('QMD package directory',{exact:false}).fill(resolve(values.qmd));await documents.getByLabel('LanceDB package directory',{exact:false}).fill(resolve(values.lance));await panel.getByRole('button',{name:'Apply configuration and stop services'}).click();await panel.getByRole('button',{name:'Apply configuration and stop services'}).waitFor({state:'hidden'})
 report.configured=await inspect();report.backups=readdirSync(dirname(report.configured.configurationPath)).filter(name=>name.startsWith('tools-backup-'));assert(report.backups.length>=3)
 await page.keyboard.press('Escape');await invoke('ui.sidebar',{side:'right',open:true,tab:'search',width:480})
 const job=await invoke('tool.call',{workspacePath:project,id:'documents',operation:'index',arguments:{}});await invoke('tool.call',{workspacePath:project,id:'documents',operation:'pause',arguments:{}})
 const search=page.getByRole('region',{name:'Project search'});await search.getByRole('button',{name:'Resume document indexing'}).waitFor({timeout:30000});await search.getByText(/Document index: paused/).waitFor();await page.screenshot({path:join(evidence,'index-paused.png')});await search.getByRole('button',{name:'Resume document indexing'}).click();await search.getByText(/Document index: ready/).waitFor({timeout:45000});report.resumed=await invoke('tool.call',{workspacePath:project,id:'documents',operation:'progress',arguments:{}});assert.equal(report.resumed.structuredContent.job,job.structuredContent.job)
 await search.getByRole('button',{name:'Stop document service'}).click();await delay(2200);assert.equal((await invoke('tool.list',{workspacePath:project})).find(service=>service.id==='documents').status,'stopped');await page.screenshot({path:join(evidence,'index-stopped.png')});report.pollingDidNotRestart=true
 if(values.backlog){
  await invoke('ui.settings.open',{section:'agents'});const board=panel.locator('details').filter({has:page.locator('summary').filter({hasText:'Native task board'})}).first();await board.locator(':scope > summary').click();await board.getByLabel('Backlog.md executable',{exact:false}).fill(resolve(values.backlog));await panel.getByRole('button',{name:'Apply configuration and stop services'}).click();await panel.getByRole('button',{name:'Apply configuration and stop services'}).waitFor({state:'hidden'});report.configured=await inspect();
  const native=(...args)=>execFileSync(resolve(values.backlog),args,{cwd:project,env:{...process.env,BACKLOG_CWD:project},stdio:'ignore'});native('init','Fixture','--defaults','--integration-mode','none','--check-branches','false','--include-remote','false','--auto-open-browser','false');native('task','create','Native configured task','--plain');await invoke('project.task-authority',{workspacePath:project,enabled:true});report.nativeTasks=await invoke('project.tasks',{workspacePath:project});assert.equal(report.nativeTasks.tasks[0].title,'Native configured task');await page.keyboard.press('Escape');
 }
 await invoke('ui.settings.open',{section:'agents'});const computer=panel.locator('details').filter({has:page.locator('summary').filter({hasText:'Computer control'})}).first();await computer.locator(':scope > summary').click();await computer.getByLabel('Enabled for this project').uncheck();await panel.getByRole('button',{name:'Apply configuration and stop services'}).click();await panel.getByRole('button',{name:'Apply configuration and stop services'}).waitFor({state:'hidden'});
 const beforeDamage=await inspect(),backup=beforeDamage.backups[0].name,damaged='{"password":"doctor-fixture-secret", broken';writeFileSync(beforeDamage.configurationPath,damaged);await panel.getByRole('button',{name:'Recheck setup'}).click();await panel.getByText(/Cannot read project tool configuration/).waitFor();assert(!(await panel.innerText()).includes('doctor-fixture-secret'));await panel.getByLabel('Review saved configuration').selectOption(backup);await panel.getByText(/original bytes will be preserved/).waitFor();assert.equal(readFileSync(beforeDamage.configurationPath,'utf8'),damaged);await page.screenshot({path:join(evidence,'repair-preview.png')});await panel.getByRole('button',{name:'Apply configuration and stop services'}).click();await panel.getByRole('button',{name:'Apply configuration and stop services'}).waitFor({state:'hidden'});report.configured=await inspect();assert.equal(report.configured.problem,null);assert(report.configured.backups.some(item=>readFileSync(join(dirname(report.configured.configurationPath),item.name),'utf8')===damaged));report.corruptConfigurationRepaired=true;
 await app.close();await open();report.afterRestart=await inspect();assert.equal(report.afterRestart.revision,report.configured.revision);assert(report.afterRestart.configuration.disabled.includes('code-graph'));
 if(values.history){
  const nativeProject=realpathSync('/tmp/donwells-strengthen-27-native/project');await invoke('repo.add',{dir:nativeProject});await page.getByTitle(nativeProject,{exact:true}).and(page.getByRole('button')).click();await invoke('ui.settings.open',{section:'agents'});
  const history=page.getByRole('region',{name:'Project tools'}).locator('details').filter({has:page.locator('summary').filter({hasText:'Native session history'})}).first();await history.locator(':scope > summary').click();await history.getByLabel('AgentsView executable',{exact:false}).fill(resolve(values.history));await history.getByLabel('OMP session roots, one per line').fill('/tmp/donwells-strengthen-27-native');await history.getByLabel('DeepSeek session roots, one per line').fill('/tmp/donwells-strengthen-09-dsh-ornith-home/sessions');await page.getByRole('button',{name:'Apply configuration and stop services'}).click();await page.getByRole('button',{name:'Apply configuration and stop services'}).waitFor({state:'hidden'});await history.getByRole('button',{name:'Reindex sessions'}).click();
  for(let i=0;i<100;i++){try{report.nativeHistory=await invoke('history.search',{workspacePath:nativeProject,query:'HISTORY_ORNITH_27'});if(report.nativeHistory.hits.length)break}catch{}await delay(100)}assert(report.nativeHistory.hits.length);await page.screenshot({path:join(evidence,'native-history-settings.png')});await history.getByRole('button',{name:'Stop service'}).click();
  const foreign=await invoke('history.search',{workspacePath:project,query:'HISTORY_ORNITH_27'}).then(()=>true,()=>false);assert.equal(foreign,false);report.historyScoped=true;await app.close();await open();report.retainedHistory=await invoke('history.search',{workspacePath:nativeProject,query:'HISTORY_ORNITH_27'});assert(report.retainedHistory.hits.length);
 }
 report.verified=true
}catch(error){report.error=error.stack;process.exitCode=1;if(page)await page.screenshot({path:join(evidence,'failure.png')}).catch(()=>{})}
finally{
 if(app){try{for(const tool of await invoke('tool.list',{workspacePath:project}))await invoke('tool.stop',{workspacePath:project,id:tool.id});for(const session of(await invoke('terminal.list')).sessions)await invoke('terminal.close',{sessionId:session.id})}catch(error){report.cleanupError=String(error)}await app.close().catch(()=>{})}
 report.idleDaemonStopped=await cleanupOwnedSmokeDaemon(profile);writeFileSync(join(evidence,'result.json'),JSON.stringify(report,null,2)+'\n')
}
