import { contextBridge, ipcRenderer } from 'electron'
import type { IpcApi, MainEvents } from '../shared/types'

const api: IpcApi = {
  browserView: request => ipcRenderer.invoke('browser:view', request),
  onBrowserView: callback => { const listener = (_event: Electron.IpcRendererEvent, message: import('@shared/browser-view').BrowserViewEvent) => callback(message); ipcRenderer.on('browser:view', listener); return () => ipcRenderer.removeListener('browser:view', listener) },
  projectMemoryStorageStatus: () => ipcRenderer.invoke('projectMemoryStorageStatus'),
  projectMemoryStorageAction: action => ipcRenderer.invoke('projectMemoryStorageAction', action),
  meta: () => ipcRenderer.invoke('meta'),
  createProject: (request) => ipcRenderer.invoke('createProject', request),
  getProjectCreationDefaults: () => ipcRenderer.invoke('getProjectCreationDefaults'),
  projectMemoryList: (request) => ipcRenderer.invoke('projectMemoryList', request),
  projectMemoryGet: (request) => ipcRenderer.invoke('projectMemoryGet', request),
  projectMemoryCreate: (request) => ipcRenderer.invoke('projectMemoryCreate', request),
  projectMemoryUpdate: (request) => ipcRenderer.invoke('projectMemoryUpdate', request),
  projectMemoryHistory: (request) => ipcRenderer.invoke('projectMemoryHistory', request),
  projectMemoryArchive: (request) => ipcRenderer.invoke('projectMemoryArchive', request),
  editorRecoveryList: () => ipcRenderer.invoke('editorRecoveryList'),
  editorRecoveryGet: (target) => ipcRenderer.invoke('editorRecoveryGet', target),
  editorRecoveryCheckpoint: (request) => ipcRenderer.invoke('editorRecoveryCheckpoint', request),
  editorRecoveryClear: (request) => ipcRenderer.invoke('editorRecoveryClear', request),
  attentionInboxList: () => ipcRenderer.invoke('attentionInboxList'),
  attentionInboxAcknowledge: (request) => ipcRenderer.invoke('attentionInboxAcknowledge', request),
  listRepos: () => ipcRenderer.invoke('listRepos'),
  addRepo: (dir) => ipcRenderer.invoke('addRepo', dir),
  removeRepo: (repoId) => ipcRenderer.invoke('removeRepo', repoId),
  refreshRepo: (repoId) => ipcRenderer.invoke('refreshRepo', repoId),
  createWorktree: (repoId, opts) => ipcRenderer.invoke('createWorktree', repoId, opts),
  removeWorktree: (repoId, worktreePath, force) => ipcRenderer.invoke('removeWorktree', repoId, worktreePath, force),
  openTerminal: (worktreePath, cwd) => ipcRenderer.invoke('openTerminal', worktreePath, cwd),
  attachTerminal: (sessionId) => ipcRenderer.invoke('attachTerminal', sessionId),
  closeTerminal: (sessionId) => ipcRenderer.invoke('closeTerminal', sessionId),
  terminalSessions: () => ipcRenderer.invoke('terminalSessions'),
  terminalWrite: (sessionId, data) => ipcRenderer.invoke('terminalWrite', sessionId, data),
  scanWorktree: (worktreePath) => ipcRenderer.invoke('scanWorktree', worktreePath),
  terminalResize: (sessionId, cols, rows) => ipcRenderer.invoke('terminalResize', sessionId, cols, rows),
  terminalInterrupt: (sessionId) => ipcRenderer.invoke('terminalInterrupt', sessionId),
  gitStatus: (worktreePath) => ipcRenderer.invoke('gitStatus', worktreePath),
  gitStage: (worktreePath, paths) => ipcRenderer.invoke('gitStage', worktreePath, paths),
  gitUnstage: (worktreePath, paths) => ipcRenderer.invoke('gitUnstage', worktreePath, paths),
  gitDiscard: (worktreePath, paths) => ipcRenderer.invoke('gitDiscard', worktreePath, paths),
  gitCommit: (worktreePath, message, options) => ipcRenderer.invoke('gitCommit', worktreePath, message, options),
  gitPush: (worktreePath) => ipcRenderer.invoke('gitPush', worktreePath),
  gitPull: (worktreePath) => ipcRenderer.invoke('gitPull', worktreePath),
  gitFetch: (worktreePath) => ipcRenderer.invoke('gitFetch', worktreePath),
  gitBranches: (worktreePath) => ipcRenderer.invoke('gitBranches', worktreePath),
  gitCheckout: (worktreePath, branch) => ipcRenderer.invoke('gitCheckout', worktreePath, branch),
  gitCreateBranch: (worktreePath, branch, startPoint) => ipcRenderer.invoke('gitCreateBranch', worktreePath, branch, startPoint),
  gitHistory: (worktreePath, options) => ipcRenderer.invoke('gitHistory', worktreePath, options),
  gitDiff: (worktreePath, relPath) => ipcRenderer.invoke('gitDiff', worktreePath, relPath),
  listWorkspaceDirectory: (workspacePath, request) => ipcRenderer.invoke('listWorkspaceDirectory', workspacePath, request),
  searchWorkspaceFiles: (workspacePath, request) => ipcRenderer.invoke('searchWorkspaceFiles', workspacePath, request),
  projectSessionHistoryIndex: path => ipcRenderer.invoke('projectSessionHistoryIndex', path),
  projectSessionHistorySearch: (path, query) => ipcRenderer.invoke('projectSessionHistorySearch', path, query),
  projectSessionHistoryGet: (path, id) => ipcRenderer.invoke('projectSessionHistoryGet', path, id),
  projectToolsList: path => ipcRenderer.invoke('projectToolsList', path),
  projectToolCall: (...args) => ipcRenderer.invoke('projectToolCall', ...args),
  projectToolStop: (...args) => ipcRenderer.invoke('projectToolStop', ...args),
  searchWorkspaceContent: (workspacePath, requestId, request) => ipcRenderer.invoke('searchWorkspaceContent', workspacePath, requestId, request),
  cancelWorkspaceContentSearch: requestId => ipcRenderer.invoke('cancelWorkspaceContentSearch', requestId),
  createWorkspaceEntry: (workspacePath, request) => ipcRenderer.invoke('createWorkspaceEntry', workspacePath, request),
  moveWorkspaceEntry: (workspacePath, request) => ipcRenderer.invoke('moveWorkspaceEntry', workspacePath, request),
  duplicateWorkspaceEntry: (workspacePath, request) => ipcRenderer.invoke('duplicateWorkspaceEntry', workspacePath, request),
  deleteWorkspaceEntry: (workspacePath, request) => ipcRenderer.invoke('deleteWorkspaceEntry', workspacePath, request),
  readFile: (worktreePath, relPath) => ipcRenderer.invoke('readFile', worktreePath, relPath),
  readFileAtRef: (worktreePath, relPath, ref) => ipcRenderer.invoke('readFileAtRef', worktreePath, relPath, ref),
  writeFile: (worktreePath, relPath, content, expectedRevision) => ipcRenderer.invoke('writeFile', worktreePath, relPath, content, expectedRevision),
  readPreviewImage: (worktreePath, documentPath, source) => ipcRenderer.invoke('readPreviewImage', worktreePath, documentPath, source),
  readBinaryPreview: (workspacePath, request) => ipcRenderer.invoke('readBinaryPreview', workspacePath, request),
  cancelBinaryPreview: (generation) => ipcRenderer.invoke('cancelBinaryPreview', generation),
  applyAppearance: (request) => ipcRenderer.invoke('applyAppearance', request),
  getSettings: () => ipcRenderer.invoke('getSettings'),
  getWorkspaceSession: () => ipcRenderer.invoke('getWorkspaceSession'),
  saveWorkspaceSession: (ws) => ipcRenderer.invoke('saveWorkspaceSession', ws),
  setSettings: (patch) => ipcRenderer.invoke('setSettings', patch),
  resetSettings: (request) => ipcRenderer.invoke('resetSettings', request),
  browserHistoryList: () => ipcRenderer.invoke('browserHistoryList'),
  browserHistoryRecord: (entry) => ipcRenderer.invoke('browserHistoryRecord', entry),
  browserHistoryClear: () => ipcRenderer.invoke('browserHistoryClear'),
  listAgents: () => ipcRenderer.invoke('listAgents'),
  projectTasksInspect: path => ipcRenderer.invoke('projectTasksInspect', path),
  projectTaskAuthority: (path, enabled) => ipcRenderer.invoke('projectTaskAuthority', path, enabled),
  projectTaskTool: (path, tool) => ipcRenderer.invoke('projectTaskTool', path, tool),
  agentStart: (workspacePath, command, task) => ipcRenderer.invoke('agentStart', workspacePath, command, task),
  agentList: () => ipcRenderer.invoke('agentList'),
  agentInterrupt: (sessionId) => ipcRenderer.invoke('agentInterrupt', sessionId),
  agentStop: (sessionId) => ipcRenderer.invoke('agentStop', sessionId),
  projectHandoffExport: (...args) => ipcRenderer.invoke('projectHandoffExport', ...args),
  projectHandoffList: (...args) => ipcRenderer.invoke('projectHandoffList', ...args),
  projectHandoffGet: (...args) => ipcRenderer.invoke('projectHandoffGet', ...args),
  projectHandoffCreate: (...args) => ipcRenderer.invoke('projectHandoffCreate', ...args),
  projectHandoffAccept: (...args) => ipcRenderer.invoke('projectHandoffAccept', ...args),
  projectHandoffSupersede: (...args) => ipcRenderer.invoke('projectHandoffSupersede', ...args),
  agentConfigureMemory: (workspacePath, provider, launchArgs) => ipcRenderer.invoke('agentConfigureMemory', workspacePath, provider, launchArgs),
  agentDismiss: (sessionId) => ipcRenderer.invoke('agentDismiss', sessionId),
  agentDeliver: (request) => ipcRenderer.invoke('agentDeliver', request),
  openExternal: (url) => ipcRenderer.invoke('openExternal', url),
  pickDirectory: () => ipcRenderer.invoke('pickDirectory'),
  secretSet: (key, value) => ipcRenderer.invoke('secretSet', key, value),
  secretGet: (key) => ipcRenderer.invoke('secretGet', key),
  secretDelete: (key) => ipcRenderer.invoke('secretDelete', key),
  secretAvailable: () => ipcRenderer.invoke('secretAvailable'),
  skillPackagesList: (request) => ipcRenderer.invoke('skillPackagesList', request),
  skillPackagesPrepare: (request) => ipcRenderer.invoke('skillPackagesPrepare', request),
  skillPackagesApply: (request) => ipcRenderer.invoke('skillPackagesApply', request),
  skillPackagesRead: (request) => ipcRenderer.invoke('skillPackagesRead', request),
  skillPackagesPrepareUpdate: (request) => ipcRenderer.invoke('skillPackagesPrepareUpdate', request),
  skillPackagesPrepareRemove: (request) => ipcRenderer.invoke('skillPackagesPrepareRemove', request),
  skillPackagesRemove: (request) => ipcRenderer.invoke('skillPackagesRemove', request),
  scheduledRunsList: () => ipcRenderer.invoke('scheduledRunsList'),
  scheduledRunSave: (input) => ipcRenderer.invoke('scheduledRunSave', input),
  scheduledRunSetEnabled: (id, enabled) => ipcRenderer.invoke('scheduledRunSetEnabled', id, enabled),
  scheduledRunDuplicate: (id) => ipcRenderer.invoke('scheduledRunDuplicate', id),
  scheduledRunDelete: (id) => ipcRenderer.invoke('scheduledRunDelete', id),
  scheduledRunRunNow: (id) => ipcRenderer.invoke('scheduledRunRunNow', id),
  scheduledRunCancel: (executionId) => ipcRenderer.invoke('scheduledRunCancel', executionId),
  scheduledRunHistory: (id) => ipcRenderer.invoke('scheduledRunHistory', id),
  verificationScripts: (path) => ipcRenderer.invoke('verificationScripts',path),
  verificationRun: (path,script) => ipcRenderer.invoke('verificationRun',path,script),
  verificationList: (path,verifyArtifacts) => ipcRenderer.invoke('verificationList',path,verifyArtifacts),
  verificationAttach: (path,runId,taskId,artifact) => ipcRenderer.invoke('verificationAttach',path,runId,taskId,artifact),
  parallelRunsList: () => ipcRenderer.invoke('parallelRunsList'),
  parallelRunStart: (input) => ipcRenderer.invoke('parallelRunStart', input),
  parallelRunRetry: (id, taskIds) => ipcRenderer.invoke('parallelRunRetry', id, taskIds),
  parallelRunCancel: (id) => ipcRenderer.invoke('parallelRunCancel', id),
  parallelRunDelete: (id) => ipcRenderer.invoke('parallelRunDelete', id),
  diffReviewList: (request) => ipcRenderer.invoke('diffReviewList', request),
  diffReviewCreate: (request) => ipcRenderer.invoke('diffReviewCreate', request),
  diffReviewUpdate: (request) => ipcRenderer.invoke('diffReviewUpdate', request),
  diffReviewDelete: (request) => ipcRenderer.invoke('diffReviewDelete', request),
  setAttention: (state) => ipcRenderer.send('attention', state),
  onBrowserCommand: (cb) => {
    const listener = (_e: unknown, env: { id: string; cmd: import('@shared/types').BrowserCommand }) => cb(env)
    ipcRenderer.on('browser:command', listener)
    return () => ipcRenderer.removeListener('browser:command', listener)
  },
  resolveBrowserCommand: (id, result) => ipcRenderer.send('browser:command:result', id, result),
  browserRouterReady: () => ipcRenderer.send('browser:router-ready'),
  uiRouterReady: () => ipcRenderer.send('ui:router-ready'),
  onUiCommand: (cb) => {
    const listener = (_e: unknown, env: { id: string; cmd: import('@shared/types').UiCommand }) => cb(env)
    ipcRenderer.on('ui:command', listener)
    return () => ipcRenderer.removeListener('ui:command', listener)
  },
  resolveUiCommand: (id, result) => ipcRenderer.send('ui:command:result', id, result),
  on: <K extends keyof MainEvents>(channel: K, cb: (payload: MainEvents[K]) => void) => {
    const listener = (_e: unknown, payload: MainEvents[K]) => cb(payload)
    ipcRenderer.on(channel, listener)
    return () => ipcRenderer.removeListener(channel, listener)
  }
}

contextBridge.exposeInMainWorld('donwells', api)
